### ISSUE TITLE
Clean styles file "app.css"

### ISSUE THREAD

**Issue by leogtzr** [leogtzr/vecin#6]
There is still stuff from the previous app, e.g:
```CSS
.search-container {
    margin: 0 auto;
}

.search-input-group, .top-5-books > div {
    width: 100%;
}
```
